### ISSUE TITLE
how to set breakpoint?

### ISSUE THREAD

**Issue by nzcv** [necauqua/jdwp#6]

**Comment by necauqua** [comment]
Hello!
As you can see in the [readme](https://github.com/necauqua/jdwp#readme), this crate is _very_ incomplete (and not even published on crates.io - I've only claimed the name there), and does not implement the EventRequest or Event command sets (which are sets of commands needed to set breakpoints and receive breakpoint events respectively, among other events).

Only the [Virtual Machine command set](https://github.com/necauqua/jdwp/blob/main/src/commands/virtual_machine.rs) is actually implemented, which just allows you to inspect and redefine classes.

Whenever it does implement the needed command sets - you'll be able to work with breakpoints, but currently this crate is pretty useless.
